version: "3.7"
services:
  registry:
    image: registry:2
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - registry_net
  ui:
    image: jc21/registry-ui
    environment:
      - NODE_ENV=production
      - REGISTRY_HOST=registry:5000
      - REGISTRY_SSL=
      - REGISTRY_DOMAIN=
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    restart: on-failure
    networks:
      - registry_net
  proxy:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - registry_net
    ports:
      - 80:80
volumes:
  registry_data:
networks:
  registry_net: